/**
 * @param {Translation} translation
 */
export default function (translation) {
    translation.addStrings('en', {
        'app.select.value.default.name': 'Select',
        'app.settings.mqtt.host_label': 'Host',
        'app.settings.mqtt.pass_label': 'Password',
        'app.settings.mqtt.title': 'MQTT Broker',
        'app.settings.mqtt.user_label': 'Username',
        'app.settings.title': 'Settings',
        'app.shortcuts.modal.shortcut_name.text': 'Name',
        'app.shortcuts.modal.shortcut_retain.text': 'Retain',
        'app.shortcuts.modal.shortcut_payload.text': 'Payload',
        'app.shortcuts.modal.shortcut_topic.text': 'Topic',
        'app.shortcuts.modal.shortcut_events.text': 'Events',
        'app.shortcuts.title': 'Shortcuts',
        'app.shortcuts.title_new': 'New Shortcut',
        'button.save.title': 'Save',
        'menu.title_apps': 'Apps',
        'modal.button_close': 'Cancel',
        'modal.button_submit': 'Submit',
        'app.dashboard_editor.title': 'Dashboard Editor',
        'app.dashboard.details.edit.input_order.label': 'Order',
        'app.dashboard.details.edit.input_size.label': 'Size',
        'app.dashboard.detail.edit_group.title': 'Edit',
        'app.dashboard.detail.create_group_item.title': 'Create group item',
        'app.dashboard.detail.create_group.title': 'Create group',
        'app.dashboard.detail.edit_group.elements_title': 'UI Elements',
        'app.dashboard.detail.add_group_item.name_title': 'Item Name',
    });
    translation.addStrings('de', {
        'app.select.value.default.name': 'Wählen',
        'app.settings.mqtt.host_label': 'Adresse',
        'app.settings.mqtt.pass_label': 'Passwort',
        'app.settings.mqtt.title': 'MQTT Server',
        'app.settings.mqtt.user_label': 'Nutzername',
        'app.settings.title': 'Einstellungen',
        'app.shortcuts.modal.shortcut_name.text': 'Name',
        'app.shortcuts.title': 'Verknüpfungen',
        'app.shortcuts.title_new': 'Neue Verknüpfung',
        'button.save.title': 'Speichern',
        'menu.title_apps': 'Anwendungen',
        'modal.button_close': 'Abbrechen',
        'modal.button_submit': 'Absenden',
        'app.dashboard.details.edit.input_order.label': 'Position',
        'app.dashboard.details.edit.input_size.label': 'Größe',
        'app.dashboard.detail.edit_group.title': 'Bearbeite',
        'app.dashboard.detail.create_group_item.title': 'Gruppen-Item erstellen',
        'app.dashboard.detail.create_group.title': 'Gruppe erstellen',
        'app.dashboard.detail.edit_group.elements_title': 'UI Elemente',
        'app.dashboard.detail.add_group_item.name_title': 'Item Name'
        ,
    });
}
