import type { App } from 'vue';
import ElAlert from '@element-plus/alert';
import ElAvatar from '@element-plus/avatar';
import ElAutocomplete from '@element-plus/autocomplete';
import ElBacktop from '@element-plus/backtop';
import ElButton from '@element-plus/button';
import ElBadge from '@element-plus/badge';
import ElCard from '@element-plus/card';
import ElCheckbox from '@element-plus/checkbox';
import ElDropdown from '@element-plus/dropdown';
import ElTag from '@element-plus/tag';
import ElLayout from '@element-plus/layout';
import ElDivider from '@element-plus/divider';
import ElCarousel from '@element-plus/carousel';
import ElTimeline from '@element-plus/timeline';
import ElProgress from '@element-plus/progress';
import ElBreadcrumb from '@element-plus/breadcrumb';
import ElIcon from '@element-plus/icon';
import ElImage from '@element-plus/image';
import ElLink from '@element-plus/link';
import ElRate from '@element-plus/rate';
import ElSwitch from '@element-plus/switch';
import ElContainer from '@element-plus/container';
import ElNotification from '@element-plus/notification';
import ElPageHeader from '@element-plus/page-header';
import ElRadio from '@element-plus/radio';
import ElScrollBar from '@element-plus/scrollbar';
import ElSteps from '@element-plus/steps';
import ElCollapse from '@element-plus/collapse';
import ElTimePicker from '@element-plus/time-picker';
import ElDatePicker from '@element-plus/date-picker';
import ElTabs from '@element-plus/tabs';
import ElTooltip from '@element-plus/tooltip';
import ElSlider from '@element-plus/slider';
import ElInput from '@element-plus/input';
import ElTransfer from '@element-plus/transfer';
import ElDialog from '@element-plus/dialog';
import ElCalendar from '@element-plus/calendar';
import ElInfiniteScroll from '@element-plus/infinite-scroll';
import ElMessage from '@element-plus/message';
import ElDrawer from '@element-plus/drawer';
import ElPopconfirm from '@element-plus/popconfirm';
import ElForm from '@element-plus/form';
import ElUpload from '@element-plus/upload';
import ElTree from '@element-plus/tree';
import ElColorPicker from '@element-plus/color-picker';
import ElSelect from '@element-plus/select';
import ElTimeSelect from '@element-plus/time-select';
import ElPagination from '@element-plus/pagination';
import ElInputNumber from '@element-plus/input-number';
export { ElAlert, ElAvatar, ElAutocomplete, ElBacktop, ElLayout, ElButton, ElBadge, ElCard, ElCheckbox, ElDivider, ElDropdown, ElTag, ElCarousel, ElTimeline, ElProgress, ElBreadcrumb, ElIcon, ElImage, ElLink, ElRate, ElSwitch, ElContainer, ElNotification, ElPageHeader, ElScrollBar, ElSteps, ElRadio, ElCollapse, ElTimePicker, ElDatePicker, ElTabs, ElTooltip, ElSlider, ElInput, ElTransfer, ElDialog, ElCalendar, ElInfiniteScroll, ElMessage, ElDrawer, ElPopconfirm, ElForm, ElUpload, ElTree, ElColorPicker, ElSelect, ElTimeSelect, ElPagination, ElInputNumber, };
declare const elementUI: {
    install: (app: App) => void;
};
export default elementUI;
